version: '3.8'

services:
  tech:
    build:
      context: .
      dockerfile: ./apps/tech/Dockerfile
      target: development
    command: pnpm run start:dev tech
    env_file:
      - ./apps/tech/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/user/src/app
  
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user
    env_file:
      - .:/apps/user/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  postgres1:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:13
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"

volumes:
  pgdata1:
  pgdata2:
